import { test, expect } from '@playwright/test';
const IGNORE = ['WebGL','webgl','context could not be created','Error creating WebGL','setClearColor','THREE.WebGLRenderer','GPU','RENDER WARNING','framebuffer','BindToCurrentSequence','403','404','MIME type','mediapipe','cdn.jsdelivr.net','Refused to execute script','Failed to load resource','gestureController','Cannot read properties of undefined','position'];
function isCritical(t) { return !IGNORE.some(p => t.includes(p)); }
async function safeEval(page, fn) { try { return await page.evaluate(fn); } catch(e) { if(e.message.includes('Execution context')) { await page.waitForTimeout(2000); try { return await page.evaluate(fn); } catch(e2) { return null; } } return null; } }
test.describe('CRITICAL: Game Startup Verification', () => {
    let ce=[], pe=[];
    test.beforeEach(async ({ page }) => { ce=[]; pe=[]; page.on('console',m=>{if(m.type()==='error')ce.push({text:m.text()});}); page.on('pageerror',e=>{pe.push({message:e.message});}); });
    test('Game loads without JS errors', async ({ page }) => { await page.goto('/index.html',{waitUntil:'domcontentloaded'}); await page.waitForSelector('canvas',{timeout:30000}).catch(()=>null); await page.waitForTimeout(6000); expect(await safeEval(page,()=>typeof THREE!=='undefined')).toBe(true); expect(await safeEval(page,()=>typeof gameState!=='undefined')).toBe(true); expect(await safeEval(page,()=>typeof window.startGame==='function')).toBe(true); expect(pe.filter(e=>e.message.includes('has already been declared')).length).toBe(0); expect(pe.filter(e=>isCritical(e.message)).length+ce.filter(e=>isCritical(e.text)).length).toBe(0); });
    test('No duplicate identifier errors', async ({ page }) => { const s=[]; page.on('pageerror',e=>{if(e.message.includes('already been declared')||e.message.includes('SyntaxError'))s.push(e.message);}); await page.goto('/index.html',{waitUntil:'domcontentloaded'}); await page.waitForTimeout(3000); expect(s.length).toBe(0); });
    test('Required global functions exist', async ({ page }) => { await page.goto('/index.html',{waitUntil:'domcontentloaded'}); await page.waitForSelector('canvas',{timeout:30000}).catch(()=>null); await page.waitForTimeout(6000); const f=await safeEval(page,()=>['startGame','submitHighscore','skipHighscore'].map(n=>({name:n,exists:typeof window[n]==='function'}))); expect(f).not.toBeNull(); expect(f.find(x=>x.name==='startGame').exists).toBe(true); });
    test('No Supabase CDN conflict', async ({ page }) => { const s=[]; page.on('pageerror',e=>{if(e.message.toLowerCase().includes('supabase')||e.message.includes("'supabase'"))s.push(e.message);}); await page.goto('/index.html',{waitUntil:'domcontentloaded'}); await page.waitForTimeout(3000); expect(s.length).toBe(0); });
    test('Diagnostic - all errors', async ({ page }) => { const ep=[],ec=[]; page.on('pageerror',e=>{ep.push({message:e.message});}); page.on('console',m=>{if(m.type()==='error')ec.push(m.text());}); await page.goto('/index.html',{waitUntil:'domcontentloaded'}); await page.waitForTimeout(6000); expect(ep.filter(e=>isCritical(e.message)).length).toBe(0); });
});
