import { test, expect } from '@playwright/test';
const IGNORE = ['WebGL','webgl','context could not be created','THREE.WebGLRenderer','setClearColor','GPU','RENDER WARNING','framebuffer','BindToCurrentSequence','403','404','MIME type','mediapipe','cdn.jsdelivr.net','Refused to execute script','Failed to load resource','gestureController','Cannot read properties of undefined','position'];
function isCritical(t) { return !IGNORE.some(p => t.includes(p)); }
async function safeEval(page, fn) { try { return await page.evaluate(fn); } catch(e) { if(e.message.includes('Execution context')) { await page.waitForTimeout(2000); try { return await page.evaluate(fn); } catch(e2) { return null; } } return null; } }
test.describe('CRITICAL: Game Start Validation', () => {
    let ce=[], pe=[];
    test.beforeEach(async ({ page }) => { ce=[]; pe=[]; page.on('console',m=>{if(m.type()==='error')ce.push(m.text());}); page.on('pageerror',e=>{pe.push(e.message);}); await page.goto('/index.html',{waitUntil:'domcontentloaded'}); await page.waitForTimeout(6000); });
    test('No critical errors', async ({ page }) => { expect([...ce,...pe].filter(isCritical)).toHaveLength(0); });
    test('Start button visible', async ({ page }) => { const m=await page.locator('#menu').isVisible().catch(()=>false); if(!m){console.log('Menu hidden');expect(await safeEval(page,()=>typeof window.startGame==='function')).toBe(true);return;} const b=page.locator('#menu button'); await expect(b.first()).toBeVisible({timeout:5000}); const t=await b.first().textContent(); expect(t).toContain('SPIEL STARTEN'); });
    test('Audio system available', async ({ page }) => { expect(await safeEval(page,()=>typeof audioManager!=='undefined')).toBe(true); });
    test('Game UI elements', async ({ page }) => { const u=await safeEval(page,()=>({s:document.getElementById('score')!==null,sp:document.getElementById('speed')!==null,l:document.getElementById('lives')!==null,t:document.getElementById('timeRemaining')!==null,k:document.getElementById('kiwiCount')!==null,b:document.getElementById('broccoliCount')!==null})); expect(u).not.toBeNull(); expect(u.s).toBe(true); expect(u.sp).toBe(true); expect(u.l).toBe(true); expect(u.t).toBe(true); expect(u.k).toBe(true); expect(u.b).toBe(true); });
    test('CRITICAL: Game starts', async ({ page }) => { expect(await safeEval(page,()=>typeof window.startGame==='function')).toBe(true); const m=await page.locator('#menu').isVisible().catch(()=>false); if(m){await page.locator('#menu button').first().click();} await page.waitForTimeout(2000); expect([...ce,...pe].filter(isCritical)).toHaveLength(0); });
});
